### ISSUE TITLE
 TypeScript compatibility with `node16` or `nodenext` moduleResolution.

### ISSUE THREAD

**Issue by kaungcue** [drenther/use-custom-event#1]
Types are not available when our ts project is configured with `"moduleResolution": "Node16" | "NodeNext" | "Bundler"`

https://replit.com/@kaungsithar/ts-support#tsconfig.json

<img width="866" alt="image" src="https://github.com/drenther/use-custom-event/assets/131878330/8dc1a7d4-20a7-4f5b-a686-91c74ffe566f">

**Comment by drenther** [comment]
Fix pushed out in [v1.1.0](https://github.com/drenther/use-custom-event/releases/tag/v1.1.0)
